kind: Service
apiVersion: v1
metadata:
  # tibero cannot use dns name if name has minus sign.
  # kubernetes DNS name only use alphabet, number, minus sign(-)
  # DO NOT USE minus sign in here!
  name: tiberolocaldns
spec:
  selector:
    lb: tibero-db
  clusterIP: None
