apiVersion: v1
kind: Service
metadata:
  name: hive
  labels:
      app: hive
spec:
  type: NodePort
  selector:
      app: hive
  ports:
    - name: thrift
      port: 9852
      targetPort: 9852
      protocol: TCP
    - name: http
      protocol: TCP
      port: 10003
      targetPort: 10002
    - name: hiveserver2
      protocol: TCP
      port: 10000
      targetPort: 10000
    - name: hcatalog
      port: 9083
      targetPort: 9083
