image: biqa.tmax.com/v20.5.0.4.0/hyperdata20.5_virtualization:20230804_v1

proxy:
  bodysize: 0
  # minutes
  timeout: 1800

server:
  port: 8100
  servlet:
    contextPath: /hyperdata20

db:
  address: tiberolocaldns
  port: 8629
  sid: tibero

pvc:
  name: tibero-pvc-db
  mountPath: /db

resources:
  requests:
    cpu: 1
    memory: 2Gi
  limits:
    cpu: 1
    memory: 2Gi

hyperdata:
  address: hyperdata-svc-hd
  port: 8080

loadBalancer:
  enabled: false
  ip: 192.168.179.38 #하이퍼데이터 로드밸런서 ip랑 같아야 함
  extport: 8500

logging:
  path: virtualization/logs

version:
  major: 20
