apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hyperdata-system.fullname" . }}
data:
  application.yml: |
    server:
      port: {{ .Values.server.port }}
      servlet:
        context-path: {{ .Values.server.servlet.contextPath }}
      tomcat:
        remoteip:
          remote-ip-header: X-Forwarded-For
    logging:
      config: {{ .Values.logging.config }}
    spring:
      config:
        use-legacy-processing: true
      profiles:
        active: {{ .Values.spring.profiles.active }}
      servlet:
        multipart:
          max-file-size: {{ .Values.spring.servlet.multipart.maxFileSize }}
          max-request-size: {{ .Values.spring.servlet.multipart.maxRequestSize }}
      datasource:
        username: {{ .Values.spring.datasource.username }}
        password: {{ .Values.spring.datasource.password }}
        url: {{ .Values.spring.datasource.url }}
        driver-class-name: {{ .Values.spring.datasource.driverClassName }}
        hikari:
          jdbcUrl: {{ .Values.spring.datasource.hikari.jdbcUrl }}
          driver-class-name: {{ .Values.spring.datasource.hikari.driverClassName }}
      rabbitmq:
        enable: {{ .Values.spring.rabbitmq.enable }}
        host: {{ .Values.spring.rabbitmq.host }}
        port: {{ .Values.spring.rabbitmq.port }}
        username: {{ .Values.spring.rabbitmq.username }}
        password: {{ .Values.spring.rabbitmq.password }}
      mail:
        enable: {{ .Values.spring.mail.enable}}
        host: {{ .Values.spring.mail.host}}
        port: {{ .Values.spring.mail.port}}
        properties:
          mail:
            debug: {{ .Values.spring.mail.properties.mail.debug}}
            smtp:
              connection-timeout: {{ .Values.spring.mail.properties.mail.smtp.connectionTimeout}}
              auth: {{ .Values.spring.mail.properties.mail.smtp.auth}}
              starttls:
                enable: {{ .Values.spring.mail.properties.mail.smtp.starttls.enable}}
              ssl:
                enable: {{ .Values.spring.mail.properties.mail.smtp.ssl.enable}}
        username: {{ .Values.spring.mail.username}}
        password: {{ .Values.spring.mail.password}}
      mvc:
        log-request-details: {{ .Values.spring.mvc.logRequestDetails}}
        log-resolved-exception: {{ .Values.spring.mvc.logResolvedException}}

      jpa:
        hibernate:
          naming:
            physical-strategy: {{ .Values.spring.jpa.hibernate.naming.physicalStrategy}}
            implicit-strategy: {{ .Values.spring.jpa.hibernate.naming.implicitStrategy}}
        showSql: {{ .Values.spring.jpa.showSql}}
        properties:
          hibernate:
            format-sql: {{ .Values.spring.jpa.properties.hibernate.formatSql}}
        database-platform: {{ .Values.spring.jpa.databasePlatform}}
    ##### Web Server Config ########################################
    ws:
      default: {{ .Values.ws.default}}
      profiles: {{ .Values.ws.profiles}}
    ### TIBERO
    tibero:
      ip: {{ .Values.tibero.ip}}
      port: {{ .Values.tibero.port}}
      username: {{ .Values.tibero.username}}
      password: {{ .Values.tibero.password}}
      sid: {{ .Values.tibero.sid}}
    ###Kubernetes
    kubernetes:
      config:
        type: kubernetes
      meta:
        name:
          namespace:
            hyperdata: {{ .Release.Namespace }}
          rbac:
            cluster-role: {{ .Values.kubernetes.meta.name.rbac.clusterRole}}
            cluster-role-binding: {{ .Values.kubernetes.meta.name.rbac.clusterRoleBinding}}
            service-account: {{ .Values.kubernetes.meta.name.rbac.serviceAccount}}
          pvc:
            ozone: {{ .Values.kubernetes.meta.name.pvc.ozone}}
        replicas: {{ .Values.kubernetes.meta.replicas}}

    ### keycloak ################
    keycloak:
      enabled: {{ .Values.keycloak.enabled}}
      realm: {{ .Values.keycloak.realm}}
      auth-server-url: {{ .Values.keycloak.authServerUrl}}
      ssl-required: {{ .Values.keycloak.sslRequired}}
      resource: {{ .Values.keycloak.resource}}
      credentials:
        secret: {{ .Values.keycloak.secret}}
      use-resource-role-mappings: {{ .Values.keycloak.useResourceRoleMappings}}
      bearer-only: {{ .Values.keycloak.bearerOnly}}
    ### keycloak end ################

    ##ozone##
    ozone:
      config:
        host: {{ .Values.ozone.config.host}}
        port: {{ .Values.ozone.config.port}}
    customAddon:
      enable: {{ .Values.customAddon.enabled }}
      url: {{ .Values.customAddon.externalDetail }}
