apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hyperdata-system.fullname" . }}-auth-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "{{ .Values.proxy.bodysize }}"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{ .Values.proxy.timeout }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ .Values.proxy.timeout }}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{ .Values.proxy.timeout }}"
    # 1팀 인증 관련 설정
    nginx.ingress.kubernetes.io/auth-url: "http://hyperdata-system-svc.{{ .Release.Namespace }}.svc.cluster.local:8100/hyperdata/api/v1/gateway/auth"
    nginx.ingress.kubernetes.io/auth-response-headers: hdUserRole,hdAdminRole,hdManagementPermission,hdProjectManager
spec:
  tls:
    - secretName: istio.hyperdata-nginx-ingress-nginx
  rules:
    -  http:
         paths:
           - path: /hyperdata/api/v1/system/(.*)
             pathType: Prefix
             backend:
               service:
                 name: {{ include "hyperdata-system.fullname" . }}-svc
                 port:
                   number: 8100
    -  http:
         paths:
           - path: /hyperdata/api/v1/search/(.*)
             pathType: Prefix
             backend:
               service:
                 name: {{ include "hyperdata-system.fullname" . }}-svc
                 port:
                   number: 8100
    -  http:
         paths:
           - path: /hyperdata/api/v1/gateway/(.*)
             pathType: Prefix
             backend:
               service:
                 name: {{ include "hyperdata-system.fullname" . }}-svc
                 port:
                   number: 8100
