apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: prometheus-ingress
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
  - http:
      paths:
      - backend:
          service:
            name: connect-to-prometheus
            port: 
              number: 9090
        path: /prometheus(/|$)(.*)
        pathType: Prefix



# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
#   name: prometheus-ingress
# spec:
#   rules:
#   - http:
#       paths:
#       - backend:
#           serviceName: connect-to-prometheus
#           servicePort: 9090
#         path: /prometheus(/|$)(.*)
#         pathType: Prefix
