apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyperdata-system.fullname" . }}-svc
  labels:
    {{- include "hyperdata-system.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hyperdata-system.selectorLabels" . | nindent 4 }}
