apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-gdb-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    #kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  tls:
    - secretName: istio.hyperdata-nginx-ingress-nginx
  rules:
   -  http:
       paths:
       - path: /neo4j(/|$)(.*)
         backend:
           serviceName: {{ template "neo4j.fullname" . }}
           servicePort: 7474

