mysql:
  username: root
  password: root
  database: mlplatform
  port: 3306
  image: biqa.tmax.com/v20.5.0.3.0/hyperdata20.5_mlplatform/mysql:20230721_v1
  resources:
    requests:
      cpu: 2
      memory: 2G
    limits:
      cpu: 2
      memory: 2G
  volume:
    size: 1G


