server:
  port: 18081

mysql:
  username: root
  password: root
  database: mlplatform
  port: 3306

rabbitmq:
  username: MLAdmin
  password: tmaxtower

loadBalancer:
  enabled: false
  ip: 192.1.1.99
  export: 8501

kubernetes:
  istio:
    ingressgateway:
      ip: hdbi-ml-stg.deliveryservice.or.kr
      port: 80


#ingressClassName: maads-dev-bi-nginx
ingressClassName: maads-stg-bi-nginx

backend:
  # image: biqa.tmax.com/hyperdata20.5_rel/hyperdata20.5_mlplatform/backend:20230623_v1
  #image: hyperregistry-dev.deliveryservice.or.kr/bi/v20.5.0.4.0/hyperdata20.5_mlplatform/backend:20230804_v1
  image: hyperregistry-stg.deliveryservice.or.kr/bi/v20.5.0.4.0/hyperdata20.5_mlplatform/backend:20230804_v1
  resources:
    limits:
      cpu: 500m
      memory: 1G
    requests:
      cpu: 500m
      memory: 1G
  volume:
    mountPath: /mlplatform
    storageClass: nfs
    size: 10Gi

# solution:
#   image: biqa.tmax.com/hyperdata20.5_rel/hyperdata20.5_mlplatform/agent:20230623_v1

# downloader:
#   image: biqa.tmax.com/hyperdata20.5_rel/hyperdata20.5_mlplatform/downloader:20230623_v1

# serving:
#   image: biqa.tmax.com/hyperdata20.5_rel/hyperdata20.5_mlplatform/kserve:20230704_v1
solution:
  image: hyperregistry-stg.deliveryservice.or.kr/bi/v20.5.0.5.0/hyperdata20.5_mlplatform/agent:20230901_v1

downloader:
  image: hyperregistry-stg.deliveryservice.or.kr/bi/v20.5.0.4.0/hyperdata20.5_mlplatform/downloader:20230804_v1

serving:
  image: hyperregistry-stg.deliveryservice.or.kr/bi/v20.5.0.4.0/hyperdata20.5_mlplatform/kserve:20230804_v1
