apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mlplatform-notebook-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - secretName: istio.{{ .Release.Namespace }}-nginx-ingress-nginx
  rules:
   -  http:
        paths:
        - path: /notebook
          backend:
            serviceName: istio-ingress-gateway-external-svc
            servicePort: 80
