image: 172.24.9.40:5000/hyperdata20.4.0.7.0_virtualization:20221028_v1

ingressClassName: "hyperdata-nginx"

proxy:
  bodysize: 1024m
  # minutes
  timeout: 1800

server:
  port: 8100
  servlet:
    contextPath: /hyperdata20

db:
  address: tiberolocaldns
  port: 8629
  sid: tibero

pvc:
  name: tibero-pvc-db
  mountPath: /db

resources:
  requests:
    cpu: 2
    memory: 5Gi
  limits:
    cpu: 2
    memory: 5Gi

proauth:
  address: hyperdata-lb-hd:28080

hyperdata:
  address: hyperdata-svc-hd
  port: 8080

loadBalancer:
  enabled: false
  ip: 172.31.45.59  #하이퍼데이터 로드밸런서 ip랑 같아야 함
  extport: 8500

logging:
  path: virtualization/logs

version:
  major: 20
