apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hyperdata-hd-redirect-ingress
  annotations:
    #kubernetes.io/ingress.class: nginx
    {{ if .Values.https.enabled }}
      {{ if .Values.webserver.fqdn.enabled }}
      nginx.ingress.kubernetes.io/rewrite-target: https://{{ .Values.webserver.fqdn.name }}:{{ .Values.webserver.port }}/hyperdata{{ .Values.version.major }}/
      {{ else }}
      nginx.ingress.kubernetes.io/rewrite-target: https://{{ .Values.webserver.ip }}:{{ .Values.webserver.port }}/hyperdata{{ .Values.version.major }}/
      {{ end }}
    {{ else }}
    nginx.ingress.kubernetes.io/rewrite-target: http://{{ .Values.webserver.ip }}:{{ .Values.webserver.port }}/hyperdata{{ .Values.version.major }}/
    {{ end }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  tls:
    - secretName: istio.hyperdata-nginx-ingress-nginx
  rules:
   -  http:
        paths:
        - path: /hyperdata{{ .Values.version.major }}
          backend:
            serviceName: hyperdata-svc-hd
            servicePort: 8080
