apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mlplatform-mysql
  name: mlplatform-mysql-pod
  annotations:
    "cni.projectcalico.org/ipAddrs": '["10.244.67.73"]'
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - maads-stg-worker04
            - maads-stg-worker05
            - maads-stg-worker06
  containers:
    - name: mlplatform-mysql-pod
      image: {{ .Values.mysql.image }}
      imagePullPolicy: "IfNotPresent"
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.username }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }}
        - name: TZ
          value: Asia/Seoul
      ports:
        - name: mysql
          containerPort: {{ .Values.mysql.port }}
      resources:
        requests:
          cpu: {{ .Values.mysql.resources.requests.cpu }}
          memory: {{ .Values.mysql.resources.requests.memory }}
        limits:
          cpu: {{ .Values.mysql.resources.limits.cpu }}
          memory: {{ .Values.mysql.resources.limits.memory }}
      volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mlplatform-mysql-pvc
