apiVersion: v1
kind: Service
metadata:
  name: mlplatform-mysql-svc
  labels:
    app: mlplatform-mysql
spec:
  ports:
    - port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.port }}
  selector:
    app: mlplatform-mysql
