# image: biqa.tmax.com/v20.5/hyperdata20.5_tibero:20230504_v1
image: hyperregistry-dev.deliveryservice.or.kr/bi/v20.5.0.5.0/hyperdata20.5_tibero:20230901_v1

loadbalancer:
  enabled: true
  ip: <YOUR EXTERNAL_IP or MASTER NODE's IP>

db:
  persistentVolumeClaimName: tibero-pvc-db
  mountPath: /db

shmSize: 3G
memoryTarget: 6G

resources:
  requests:
    cpu: 1.3
    memory: 8Gi
  limits:
    cpu: 4
    memory: 8Gi
  storage: 40Gi
