# image: biqa.tmax.com/v20.5/hyperdata20.5_front:20230504_v1
#image: hyperregistry-dev.deliveryservice.or.kr/bi/v20.5.0.5.0/hyperdata20.5_front:20230901_v2
image: hyperregistry-stg.deliveryservice.or.kr/bi/v20.5.0.5.0/hyperdata20.5_front:20230901_v2

#ingressClassName: maads-dev-bi-nginx
ingressClassName: maads-stg-bi-nginx

https:
  enabled: true

proxy:
  bodysize: 1024m
  # minutes
  timeout: 1800

resources:
  requests:
    cpu: 200m
    memory: 500Mi
  limits:
    cpu: 400m
    memory: 2Gi

db:
  mountPath: /db
  persistentVolumeClaimName: tibero-pvc-db

customLogo:
  path: /usr/share/nginx/html/res/images/common/gnb

legacy:
  #redirect to
  #redirect: https://222.122.51.145:443
  redirect: https://hdbi-stg.deliveryservice.or.kr:443
