#image: hyperregistry-dev.deliveryservice.or.kr/bi/v20.5.0.5.0/hyperdata20.5_be_common:20230912_v1
#image: hyperregistry-dev.deliveryservice.or.kr/bi/hyperdata20.5_rel_tb/be_common:230918_715c7781
image: hyperregistry-stg.deliveryservice.or.kr/bi/v20.5.0.5.0/hyperdata20.5_be_common:20230912_v1

# hd version
implementation_version: 20.5.0.5.0
implementation_date: "2023/09/04"
# sql schema version
schema_version: 20.5.0.5.0

hyperdata:
  revision:
    system: "8a556b43"
    virtualization: "9f48e6c1"
    flow: "7b7ca124"
    visualization: "a3a1bce7"


db:
  # mountPath: /db
  # # tibero headless service name
  # ip: tiberolocaldns
  # persistentVolumeClaimName: tibero-pvc-db

  mountPath: /db
  ## 동일 bd네임스페이스일 때
  #ip: tiberolocaldns.bd.svc.cluster.local
  #port: 8629

  ## 타 네임스페이스 또는 다른 호스트DB일때
  #ip: 222.122.51.14
  #port: 5555
  ip: 10.120.31.11
  port: 8629

  sid: tibero_maads_stg
  persistentVolumeClaimName: tibero-pvc-db
